@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/java.puml

title Java App Component diagram for Casino System

Container(application, "Casino application", "java", "Handles the simulation of the casino behavior", "java")

System_Boundary(app_components, "Java application"){
    Component(casino, "Casino", "Generates unique BettingRoundId")
    Component(game, "Game", "A playable game which consists of rules and rounds")
    Component(bet, "Bet", "A bet made during a betting round")
    Component(betting_round, "Betting Round", "Keeps track of bets made in a round")
    Component(player, "Player", "A simulated player that can bet in the casino (NOT IMPLEMENTED)")
    Component(cashier, "Cashier", "Distributes cards to players and keeps administration of amount of money on card")
    Component(card, "Card", "Generates unique betID's and stores money")
    Component(gaming_machine, "Gaming Machine", "A machine to connect to games")
    Component(id_factory, "ID Factory", "Factory that is used to generates IDs")
}

System_Ext(gambling_authority, "Gambling authority", "API that generates tokens and a random winning game number. It also logs the betting activity and player card information.")

Rel(application, casino, "Simulates")
Rel(casino, game, "Has multiple")
Rel(casino, cashier, "Has one")
Rel(game, betting_round, "Submits bets to")
Rel(casino, player, "Has multiple")
Rel(betting_round, gaming_machine, "Notifies winner to")
Rel(cashier, card, "Distributes")
Rel(player, cashier, "Get cards from")
Rel(cashier, player, "Hands leftover money back")
Rel(player, card, "Has")
Rel(gaming_machine, card, "Uses")
Rel(gaming_machine, bet, "Places")
Rel(app_components, gambling_authority, "Uses")
Rel(card, id_factory, "Uses")
Rel(betting_round, bet, "Consists of")
Rel(bet, id_factory, "Uses")
Rel(betting_round, id_factory, "Uses")
Rel(gaming_machine, id_factory, "Uses")
@enduml